repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: ["--unsafe"]
      - id: check-added-large-files
        args: ['--maxkb=15000']

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.0.261'
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix, --ignore, E402, --ignore, E501]

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        name: Sorts imports
        args: [
          # Align isort with black formatting
          "--multi-line=3",
          "--trailing-comma",
          "--force-grid-wrap=0",
          "--use-parentheses",
          "--profile", "black"
        ]

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        name: Fixes formatting
        language_version: python3

  - repo: https://github.com/myint/docformatter
    rev: v1.6.0
    hooks:
      - id: docformatter
        args: [--in-place]
        name: docformatter
        description: 'Formats docstrings to follow PEP 257.'
        entry: docformatter
        language: python
        types: [python]
